sonar.projectKey=Fedorieieva_bachelors-project
sonar.organization=fedorieieva

sonar.sources=riddle-generator/client/src,riddle-generator/server/src

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=riddle-generator/server/coverage/lcov.info