name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Аналіз КЛІЄНТА
      - name: Analyze Client
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Fedorieieva_bachelors-project
            -Dsonar.sources=riddle-generator/client/src
            -Dsonar.branch.name=main
          projectBaseDir: .

      # 2. Аналіз СЕРВЕРА
      - name: Analyze Server
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Fedorieieva_bachelors-project-server
            -Dsonar.sources=riddle-generator/server/src
            -Dsonar.branch.name=main
          projectBaseDir: .
